// VIM REST CONSOLE - https://github.com/diepm/vim-rest-console
// ctrj+j para rodar
// exemplos:
// https://raw.githubusercontent.com/diepm/vim-rest-console/master/sample.rest
// https://raw.githubusercontent.com/diepm/vim-rest-console/master/sample_global.rest

// Global definitions of the queries
http://localhost:5000
token = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJmcmVzaCI6ZmFsc2UsImlhdCI6MTcwNDMwNDgyMywianRpIjoiNWI0MTAzNzEtNzk3My00ZTYzLWE3NzctZTg5YjhjMzVjNTM1IiwidHlwZSI6ImFjY2VzcyIsInN1YiI6MSwibmJmIjoxNzA0MzA0ODIzLCJjc3JmIjoiZDllMDJjMzgtY2UxMC00Njk3LWFmNTYtNTUzYzBhNGMzYzMxIiwiZXhwIjoxNzA0MzA1NzIzfQ.Pvx2e9zSEKIhuKO7BLD-mFGAzkHM1VQ8TboEOyl2zvw
refresh_token = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJmcmVzaCI6ZmFsc2UsImlhdCI6MTcwNDIzOTQyMCwianRpIjoiYWM5ZGFmMzktMDI4NS00ZDlkLThiOWYtMzU4MmMzMTliMzc3IiwidHlwZSI6InJlZnJlc2giLCJzdWIiOjEsIm5iZiI6MTcwNDIzOTQyMCwiY3NyZiI6ImY1NjkxZmEwLWNiNmQtNDVjYy04MDQ4LTQ3ZTI3ODY2MmYzMyIsImV4cCI6MTcwNjgzMTQyMH0.N146Y9zqLM8wZiLN4Eo_h76y7F3nduYIh99y0au972Q
Accept: application/json
Authorization: Bearer :token
-s # silencioso
-i # fica bonito
#-v # verbose do curl
--

# Raiz
--
GET /

# Mostra todas as contas
--
GET /contas

# Mosta uma conta por id
--
GET /contas/4

# Cria uma conta
--
POST /contas
{
  "nome": "Nubank",
  "resumo": "Conta física digital",
  "valor": 1000
}

# Altera uma conta
--
PUT /contas/4
{
  "nome": "Itaú alterada",
  "resumo": "Conta alterada",
  "valor": 1000
}

# Exlui uma conta
--
DELETE /contas/3

# um teste
https://jsonplaceholder.typicode.com
GET /todos

# Cria uma operação
--
POST /operacoes
{
  "nome": "Pix",
  "resumo": "Treta",
  "custo": 100,
  "tipo": "entrada",
  "conta_id": 7
}

# Recupera todas as operacoes
--
GET /operacoes

# OPeracao por id
--
GET /operacoes/1

# Altera uma operacao
--
PUT /operacoes/8
{
  "nome": "Débito",
  "resumo": "Pagamento Água",
  "custo": 100,
  "tipo": "saida",
  "conta_id": 4
}

# Exlui uma operacao
--
DELETE /operacoes/17

# Cadastrar usuário
--
POST /usuarios
{
  "nome": "admin",
  "email": "admin@email.com",
  "senha": "letmein"
}

# Fazer login
--
POST /login
{
  "email" : "fulano@email.com",
  "senha" : "1234"
}

# Refresh token
--
Authorization: Bearer :refresh_token
POST /token/refresh
