// VIM REST CONSOLE - https://github.com/diepm/vim-rest-console
// ctrj+j para rodar
// exemplos:
// https://raw.githubusercontent.com/diepm/vim-rest-console/master/sample.rest
// https://raw.githubusercontent.com/diepm/vim-rest-console/master/sample_global.rest

// Global definitions of the queries
http://localhost:5000
Accept: application/json
-s # silencioso
-i # fica bonito
#-v # verbose do curl
--

# Raiz
--
GET /

# Mostra todas as contas
--
GET /contas

# Mosta uma conta por id
--
GET /contas/1

# Cria uma conta
--
POST /contas
{
  "nome": "Itaú",
  "resumo": "Conta física digital",
  "valor": 1000
}

# Altera uma conta
--
PUT /contas/1
{
  "nome": "Itaú alterada",
  "resumo": "Conta alterada",
  "valor": 100
}

# Exlui uma conta
--
DELETE /contas/3

# um teste
https://jsonplaceholder.typicode.com
GET /todos

# Cria uma operação
--
POST /operacoes
{
  "nome": "NomeTeste",
  "resumo": "TesteResumo",
  "custo": 1000,
  "tipo": "entrada",
  "conta_id": 2
}

# Recupera todas as operacoes
--
GET /operacoes

# OPeracao por id
--
GET /operacoes/1

# Altera uma operacao
--
PUT /operacoes/1
{
  "nome": "Itaú alterada",
  "resumo": "operacao alterada",
  "custo": 100,
  "tipo": "saida",
  "conta_id": 1
}

# Exlui uma operacao
--
DELETE /operacoes/3
